#For full documentation of the parameters in this file, and a list of all the
#parameters available for TrajectoryPlannerROS, please see
#http://www.ros.org/wiki/base_local_planner
controller_frequency: 3.0
planner_frequency: 0.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false


TrajectoryPlannerROS:
  #Set the acceleration limits of the robot
  acc_lim_theta: 3.2 
  acc_lim_x: 2.5
  acc_lim_y: 0

  #Set the velocity limits of the robot
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_y: 0.0  # zero for a differential drive robot
  min_vel_y: 0.0
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.1

  #The velocity the robot will command when trying to escape from a stuck situation
  escape_vel: -0.1
  
  #For this example, we'll use a holonomic robot
  holonomic_robot: false

  #Since we're using a holonomic robot, we'll set the set of y velocities it will sample
  #y_vels: [-0.3, -0.1, 0.1, 0.3]

  #Set the tolerance on achieving a goal
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  pdist_scale: 0.8
  gdist_scale: 0.4
  meter_scoring: true

  #We'll configure how long and with what granularity we'll forward simulate trajectories
  sim_time: 1
  sim_granularity: 0.025
  vx_samples: 5
  vy_samples: 0 # zero for a differential drive robot
  vtheta_samples: 20

  #Parameters for scoring trajectories
  occdist_scale: 0.01
  heading_lookahead: 0.325
  publish_cost_grid_pc: false

  #We'll use the Dynamic Window Approach to control instead of Trajectory Rollout for this example
  dwa: true
  simple_attractor: false

  #How far the robot must travel before oscillation flags are reset
  oscillation_reset_dist: 0.05

  #Eat up the plan as the robot moves along it
  prune_plan: true
